### PR TITLE
107 make users page in the gui more visually appealing

### PR DESCRIPTION
**Pull request by rendayigit**

### CODE REVIEW

**Comment by rendayigit** [comment]
Make the user list scroll flickable

**Comment by rendayigit** [comment]
Make the target machine list scroll flickable

**Comment by rendayigit** [comment]
Get the taget machine list of all users from the server

**Comment by rendayigit** [comment]
Make the kick buttons function

**Comment by rendayigit** [comment]
Anchor user borders to parent.right:

image

**Comment by rendayigit** [comment]
Test this implementation with multiple users!!

**Review by mrtkrkrt — APPROVED** [review]

**Comment by mrtkrkrt** [comment]
> Get the taget machine list of all users from the server

Will be solved in #129

**Comment by mrtkrkrt** [comment]
> Make the kick buttons function

Will be solved in #129

**Pull request merged**
